version: '3.8'

services:
    openelevator:
        build: 
            context: openelevator
            dockerfile: Dockerfile
            args:
                cert: /home/morpheus/priv/cert.pem
                certkey: /home/morpheus/priv/privkey.pem
                ratelimit: 100
                ratereset: 60
        ports:
            - "443:443"
        volumes:
            - elevationdata:/data
            - finaldata:/tmp
        networks:
            - backend
        
    redis:
        image: redis:latest
        restart: unless-stopped
        networks:
            - backend
    
networks:
    backend:
        driver: bridge

volumes:
    elevationdata:
        driver: local
    finaldata:
        driver: local